services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/restaurant_db
#      SPRING_DATASOURCE_USERNAME: app_user
#      SPRING_DATASOURCE_PASSWORD: password
#    depends_on:
#      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

